In [27]:
import numpy as np
from scipy import interp
import matplotlib.pyplot as plt

from sklearn import svm, datasets
from sklearn.metrics import roc_curve, auc
from sklearn.cross_validation import StratifiedKFold
from sklearn.preprocessing import label_binarize  
from sklearn.cross_validation import train_test_split
from sklearn.multiclass import OneVsRestClassifier

###lOADING the datasets
iris = datasets.load_iris()
X = iris.data
y = iris.target
#print(y)

'''
print(type(y))
print(y)
print(len(y))
'''

# Binarize the output
y = label_binarize(y, classes=[0, 1, 2])
n_classes = y.shape[1]

#print(y)
#print(n_classes)

# shuffle and split training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.5,
                                                    random_state=0)
'''
print(X_train)
print(X_test)
print(y_train)
'''
print(len(y))
print(len(y_test))  


# Learn to predict each class against the other
classifier = OneVsRestClassifier(svm.SVC(kernel='linear', probability=True,
                                 random_state=random_state))
y_score = classifier.fit(X_train, y_train).decision_function(X_test) 
print(y_test[:,1])
print(len((y_score)))
print(y_score)
print(y_score[:,1])

150
75
[0 1 0 0 0 0 0 1 1 1 0 1 1 1 1 0 1 1 0 0 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 1 0
 1 1 1 0 0 0 0 0 1 0 0 0 0 1 0 1 1 0 0 0 0 1 0 1 0 0 1 1 1 1 0 0 0 0 1 0 0
 1]
75
[[-3.58459897 -0.3117717   1.78242707]
 [-2.15411929  1.11394949 -2.393737  ]
 [ 1.89199335 -3.89592195 -6.29685764]
 [-4.52609987 -0.63396965  1.96065819]
 [ 1.39684192 -1.77722963 -6.26300472]
 [-4.29544529 -1.45402775  3.29458805]
 [ 1.60323992 -2.10413788 -6.37623283]
 [-2.65028866 -1.23852652 -0.51739315]
 [-2.86540149 -0.51681963 -0.7183625 ]
 [-1.98461469 -0.42888096 -1.70646586]
 [-3.74016002  0.4967413   0.82186705]
 [-2.38375773 -1.40490207 -0.60548048]
 [-2.64026621 -0.18334473 -0.76615536]
 [-2.6974942  -0.48066323 -0.71100338]
 [-2.68086321 -0.48076708 -0.42256446]
 [ 1.29117385 -1.00014571 -6.5048863 ]
 [-2.52210662 -0.53054572 -0.52952971]
 [-2.41636546  0.45111054 -0.99069072]
 [ 1.25101273 -0.81683438 -6.36116848]
 [ 1.74739869 -3.24428645 -6.25493848]
 [-3.18923262 -0.16043215  1.00089508]
 [-2.45158845 -0.